In [16]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from Model_Evaluate import Model_Evaluate

class KNN_Implement():
    def __init__(self):
        self.df = None
        
    def set_data_train(self, df):
        self.df = df
        
    def FixModel(self):
        knn = KNeighborsClassifier(n_neighbors = 5,metric = 'euclidean') # n_neighbors = k
        knn.fit(self.df[['latitude', 'longitude']],self.df['Abnormality'])
        return knn
                                           
    def Predict(self, unseen):
        knn = self.FixModel()
        unseen_prediction = knn.predict(unseen[['latitude', 'longitude']])

        #Hasil prediksi
        df_prediction = unseen.copy()
        df_prediction['Abnormality'] = unseen_prediction
        df_prediction.to_csv('prediction_unseen.csv')
        return df_prediction

In [17]:
df = pd.read_csv('clean_data.csv')
unseen = pd.read_csv('unseen_data.csv')
KNN = KNN_Implement()
KNN.set_data_train(df)
KNN.Predict(unseen)

,Unnamed: 0,flight_id,tanggal,latitude,longitude,heading,altitude,aircraft_code,registration,time,callsign,airline_icao,timestamp_difference,Runway,Abnormality
0,0,372547,3/6/2023 16:27,0.4523,101.4443,2,0,A320,9M-AFF,1678094854,AXM429,AXM,6,36,0
1,1,378953,3/10/2023 7:39,0.4618,101.4445,1,0,A20N,9M-AGG,1678408778,AXM427,AXM,4,36,1
2,2,380415,3/10/2023 16:39,0.4530,101.4443,2,0,A320,9M-AHY,1678441172,AXM429,AXM,5,36,0
3,3,378242,3/9/2023 16:46,0.4608,101.4445,2,0,A320,9M-AJA,1678355158,AXM429,AXM,5,36,1
4,4,379504,3/10/2023 12:04,0.4543,101.4443,2,0,AT76,9M-LMH,1678424659,MXD310,BTK,5,36,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,125,378102,3/9/2023 15:19,0.4540,101.4443,2,0,AT76,PK-WJP,1678349985,WON1239,WON,9,36,0
126,126,380839,3/10/2023 18:23,0.4635,101.4446,180,0,AT76,PK-WJP,1678447428,WON1243,WON,8,18,0
127,127,372311,3/6/2023 15:00,0.4547,101.4444,2,0,AT76,PK-WJU,1678089601,WON1239,WON,3,36,0
128,128,372896,3/6/2023 18:38,0.4546,101.4444,2,0,AT76,PK-WJU,1678102732,WON1774,WON,4,36,0
129,129,374475,3/7/2023 18:05,0.4549,101.4444,2,0,AT76,PK-WJU,1678187126,WON1243,WON,9,36,0